---
- name: install collectd marathon plugin
  become: yes
  copy:
    src: marathon-collectd-plugin.py
    dest: /usr/share/collectd/plugins/marathon.py
    mode: 0444
  tags:
    - marathon
    - collectd

- name: configure collectd marathon plugin
  become: yes
  template:
    src: marathon-collectd-plugin.conf.j2
    dest: /etc/collectd.d/marathon.conf
  notify:
    - restart collectd
  tags:
    - marathon
    - collectd
