---
- name: copy nginx configuration
  become: yes
  template:
    src: marathon.nginx.j2
    dest: /etc/marathon/marathon.nginx
  notify:
    - restart nginx-marathon
  tags:
    - marathon

- name: configure nginx
  become: yes
  command: consul-cli kv-write --token={{ consul_acl_secure_token }} secure/service/nginx/templates/marathon @/etc/marathon/marathon.nginx
  tags:
    - marathon

- name: ensure consul-nginx docker image is present
  become: yes
  command: /usr/bin/docker pull {{ consul_nginx_image }}:{{ consul_nginx_image_tag }}
  tags:
    - marathon
    - bootstrap

- name: configure nginx-marathon
  become: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: nginx-marathon.service.j2
      dest: /usr/lib/systemd/system/nginx-marathon.service
    - src: nginx-marathon.env.j2
      dest: /etc/default/nginx-marathon.env
  notify:
    - reload nginx-marathon
    - restart nginx-marathon
  tags:
    - marathon

- name: enable nginx-marathon
  become: yes
  service:
    name: nginx-marathon
    enabled: yes
    state: started
  notify:
    - restart nginx-marathon
  tags:
    - marathon
