---
- name: restart calico
  become: yes
  service:
    name: calico
    state: restarted

- name: restart mesos agent
  become: yes
  service:
    name: mesos-slave
    state: restarted
  when: "mesos_agent_active.rc == 0 and mesos_agent_active.stdout == 'active'"
  # use must_exist=no instead in ansible 2+
