- name: install latest kubernetes master 
  become: yes
  yum:
    pkg="kubernetes"
    state=latest
    enablerepo="virt7-docker-common-candidate"
  notify:
    - restart daemons
  tags:
    - master
