---
- name: restart docker
  become: yes
  service:
    name: docker
    state: restarted

- name: restart collectd
  become: yes
  service:
    name: collectd
    state: restarted

- name: restart rsyslog
  become: yes
  service:
    name: rsyslog
    state: restarted

- name: reload docker
  become: yes
  command: systemctl daemon-reload
  notify:
    - restart docker
