---
spark_versions: ["1.2.1", "1.2.2", "1.3.0", "1.3.1"]
spark_default_version: "1.3.0"
spark_install_dir: "/usr/local/share/spark"
spark_mesos_lib: "/usr/local/lib/libmesos.so"
zookeeper_master: "zookeeper.service.consul"
spark_log4j_host: localhost
spark_log4j_port: 4560
