---
- name: Wait for Kafka scheduler 
  run_once: true
  wait_for: 
    host: "{{ ansible_hostname }}"
    port: 7000 
    delay: 10
    timeout: 300
  tags:
    - kafka

- name: Add Kafka brockers  
  run_once: true
  sudo: true
  command: "./kafka-mesos.sh add  0..{{ kafka_brokers - 1 }} --heap {{ kafka_broker_heap }} --mem {{ kafka_broker_memory }} --api http://{{ ansible_hostname }}:7000"
  args:
    chdir: "{{ kafka_mesos_install_dir }}"
  tags:
    - kafka

- name: Start Kafka brockers  
  run_once: true
  sudo: true
  command: "./kafka-mesos.sh start 0..{{ kafka_brokers - 1 }} --api http://{{ ansible_hostname }}:7000"
  args:
    chdir: "{{ kafka_mesos_install_dir }}"
  tags:
    - kafka

- name: Create Kafka-Mesos configuration
  sudo: true
  template:
    src: "kafka.properties.j2"
    dest: "{{ kafka_mesos_install_dir }}/kafka-mesos.properties"
  tags:
    - kafka

# - name: Install basic Kafka client  
#   sudo: true
#   command: "./sbt update; ./sbt package"
#   args:
#     chdir: "{{ kafka_install_dir }}"
#   tags:
#     - kafka
