---
- name: Create Kafka Marathon Config  
  run_once: true
  sudo: true
  template:
    src: "kafka.json.j2"
    dest: "/tmp/kafka.json"
  tags:
    - kafka

- name: Deploy Kafka scheduler to marathon  
  run_once: true
  sudo: true
  command: "/usr/bin/curl -k --user {{ marathon_http_credentials }} -X POST -H \"Content-Type: application/json\" -d @kafka.json  https://{{ marathon }}:8080/v2/apps"
  args:
    chdir: /tmp
  tags:
    - kafka

