---
- name: copy nginx configuration
  become: yes
  template:
    src: mesos-leader.nginx.j2
    dest: /etc/mesos-leader.nginx
  tags:
    - mesos

- name: configure nginx
  become: yes
  command: consul-cli kv-write --token={{ consul_acl_secure_token }} secure/service/nginx/templates/mesos-leader @/etc/mesos-leader.nginx
  tags:
    - mesos

- name: ensure nginx-consul docker image is present
  become: yes
  command: /usr/bin/docker pull {{ consul_nginx_image }}:{{ consul_nginx_image_tag }}
  tags:
    - marathon
    - bootstrap

- name: configure nginx-mesos-leader
  become: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: nginx-mesos-leader.service.j2
      dest: /usr/lib/systemd/system/nginx-mesos-leader.service
    - src: nginx-mesos-leader.env.j2
      dest: /etc/default/nginx-mesos-leader.env
  notify:
    - reload nginx-mesos-leader
    - restart nginx-mesos-leader
  tags:
    - mesos


- name: enable nginx-mesos-leader
  become: yes
  service:
    name: nginx-mesos-leader
    enabled: yes
    state: started
  notify:
    - restart nginx-mesos-leader
  tags:
    - mesos
