---
hdfs_version: "2.6.0"
hdfs_conf_dir: "/etc/hadoop/conf"
hdfs_install_dir: "/usr/local/share"
hdfs_namenode: False
hdfs_namenode_host: host-01
hdfs_namenode_port: 8020
hdfs_hadoop_opts: "-Djava.net.preferIPv4Stack=true"


hdfs_core_properties:
  - { name: "fs.defaultFS", value: "hdfs://{{ hdfs_namenode_host }}:{{ hdfs_namenode_port }}" }
hdfs_namenode_properties:
  - { name: "dfs.name.dir", value: "/dfs/nn" }
  - { name: "dfs.data.dir", value: "/dfs/dn" }
  - { name: "dfs.replication", value: 1 }
