---
kafka_install_dir: "/usr/local/share/kafka"
kafka_mesos_install_dir: "/usr/local/share/kafka-mesos"
kafka_binary_url: "https://archive.apache.org/dist/kafka/0.8.1.1"
kafka_archive: "kafka_2.9.2-0.8.1.1.tgz"
kafka_mesos_repo: "https://github.com/mesos/kafka"
mesos_lib: "/usr/local/lib/libmesos.so"
zookeeper_master: "zookeeper.service.consul"
marathon: "marathon.service.consul"
kafka_scheduler_hostname: "kafka-mesos-scheduler.service.consul"
kafka_brokers: 3
kafka_broker_memory: 2048
kafka_broker_heap: 1024 
debug_enabled: false
