---
- name: reload systemd daemon
  become: yes
  command: systemctl daemon-reload
  tags: 
    - zookeeper 

- name: restart zookeeper
  become: yes
  service:
    name: "{{ zookeeper_service }}"
    state: restarted
  notify:
    - wait for zookeeper to listen
  tags:
    - zookeeper

- name: wait for zookeeper to listen
  command: "/usr/local/bin/zookeeper-wait-for-listen.sh {{ inventory_hostname }}"

- name: restart collectd
  become: yes
  service:
    name: collectd
    state: restarted
