---
# default is etc/utc in build 20141129 [http://cloud.centos.org/centos/7/images/]
- name: set timezone to etc/utc
  sudo: yes
  file:
    src: /usr/share/zoneinfo/Etc/UTC
    dest: /etc/localtime
    state: link
    force: yes

# add hosts to /etc/hosts
- name: configure hosts file
  sudo: yes
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ hostvars[item].ansible_default_ipv4.address }} {{ item }} {{ item }}.novalocal$"
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ item }} {{ item }}.novalocal"
    state: present
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: groups['all']

- name: install httpd-tools
  sudo: yes
  yum:
    name: httpd-tools
    state: present

- name: install nc
  sudo: yes
  yum:
    name: nmap-ncat
    state: present

- name: disable firewalld
  service:
    name: firewalld
    enabled: false
    state: stopped

- name: enable EPEL repo
  sudo: yes
  yum:
    name: epel-release
    state: latest

- name: install pip
  sudo: yes
  yum:
    name: python-pip
    state: latest

- name: update setuptools and pip
  sudo: yes
  pip:
    name: "{{ item.name }}"
    state: latest
  with_items:
    - name: pip
    - name: setuptools

- include: users.yml
- include: ssl.yml
