---
- name: download traefik package
  become: yes
  get_url:
    url: '{{ traefik_download }}'
    sha256sum: '{{ traefik_sha256_checksum }}'
    dest: /root/{{ traefik_filename }}
  tags:
    - traefik
    - bootstrap

- name: install traefik
  become: yes
  yum:
    name: /root/{{ traefik_filename }}
    state: present
  tags:
    - traefik
    - bootstrap

- name: make certificate directory
  become: yes
  file:
    dest: /etc/traefik/certs
    state: directory
  tags:
    - traefik

- name: deploy certs
  become: yes
  copy:
    src: '{{ item }}'
    dest: /etc/traefik/certs/
  with_items:
    - ssl/certs/traefik-admin.cert.pem
    - ssl/private/traefik-admin.key.pem
  tags:
    - traefik

- name: configure traefik
  become: yes
  template:
    src: traefik.toml.j2
    dest: /etc/traefik/traefik.toml
    owner: traefik
    group: traefik
    mode: 0644
    backup: yes
  notify:
    - restart traefik
  tags:
    - traefik

- name: generate traefik consul service
  become: yes
  copy:
    src: 'traefik-consul.json'
    dest: '/etc/consul/traefik.json'
  notify:
    - reload consul
  tags:
    - traefik
