---
- name: Create Hadoop HDFS data node directories
  sudo: true
  file: 
    path: "/dfs/dn"
    owner: hdfs
    group: hdfs
    state: directory
  tags:
    - hdfs

- name: Restart Hadoop HDFS data node
  sudo: true
  sudo_user: hdfs
  shell: source /etc/profile.d/hadoop.sh; hadoop-daemon.sh stop datanode; hadoop-daemon.sh start datanode
  tags:
    - hdfs
