---
- include: users.yml

- name: Install Java SDK
  sudo: true
  yum: 
    name: java-1.8.0-openjdk
    state: present

- name: Create HDFS installation directory
  sudo: true
  file: 
    path: "{{ hdfs_install_dir }}"
    owner: hdfs
    group: hdfs
    state: directory
  tags:
    - hdfs

- name: Create HDFS configuration directory
  sudo: true
  file: 
    path: "{{ hdfs_conf_dir }}"
    owner: hdfs
    group: hdfs
    state: directory
  tags:
    - hdfs

- name: Download HDFS binary
  sudo: true
  get_url:
    url: "http://apache.mirrors.pair.com/hadoop/common/hadoop-{{ hdfs_version }}/hadoop-{{ hdfs_version }}.tar.gz" 
    dest: /tmp/hadoop-{{ hdfs_version }}.tar.gz
  tags:
    - hdfs

- name: Unarchive HDFS binary
  sudo_user: hdfs
  sudo: true
  unarchive: 
    src: /tmp/hadoop-{{ hdfs_version }}.tar.gz 
    dest: "{{ hdfs_install_dir }}"
    copy: no
  tags:
    - hdfs

- name: Setup HDFS environment
  sudo: true
  template:
    src: "hadoop.sh.j2"
    dest: "/etc/profile.d/hadoop.sh"
  tags:
    - hdfs

- name: Create HDFS configuration files
  sudo: true
  template:
    src: "{{ item }}.xml.j2"
    dest: "{{ hdfs_conf_dir }}/{{ item }}.xml"
  with_items:
    - core-site
    - hdfs-site
  tags:
    - hdfs

- include: namenode.yml
  when: hdfs_namenode

- include: datanode.yml
  when: hdfs_datanode
